name: better_mvn branch
on:
  push:
    branches:
      - 'better_mvn'
jobs:
  test:
    name: unit test
    runs-on: ubuntu-latest

    steps:
    - name: check out inventory
      uses: actions/checkout@v2
      with:
        path: './inventory'
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: build common
      run: cd common && mvn clean install
    - name: install common
      run: cd common && mvn install:install-file -Dfile=./target/common-1.0-SNAPSHOT.jar  -DpomFile=./pom.xml
    - name: verify inventory
      run: cd inventory && mvn clean verify
#
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        echo ${GITHUB_REF}
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_VERSION
        cd inventory
        docker build -t stiesssh/inventory:${{ env.RELEASE_VERSION }} .
        docker push stiesssh/inventory:${{ env.RELEASE_VERSION }}
