name: main branch
on:
  push:
    branches:
#      - 'main'
      - ci

jobs: 
  test:
    name: unit test
    runs-on: ubuntu-latest

    steps:
    - name: check out inventory
      uses: actions/checkout@v2
    - run: |
        mkdir common
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - run: |
        cd ..
        pwd
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' 
        java-version: '11' 
    - run: |
        pwd  
        ls -lah  
        cat pom.xml
    - name: Maven Package
      run: mvn clean package
    - name: Maven Verify
      run: mvn clean verify
