name: main branch
on:
  push:
    branches:
      - 'main'

jobs: 
  test:
    name: unit test
    runs-on: ubuntu-latest

    steps:
    - name: check out inventory
      uses: actions/checkout@v2
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        token: ${{ secrets.foo }}
#        token: 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
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' 
        java-version: '11'     
    - name: Maven Package
      run: mvn clean package
    - name: Maven Verify
      run: mvn clean verify
