name: better_mvn branch
on:
  push:
    branches:
      - 'better_mvn'

jobs:
  test:
    name: unit test
    runs-on: ubuntu-latest

    steps:
    - name: check out inventory
      uses: actions/checkout@v2
      with:
        path: './inventory'
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - run: |
        pwd
        cd ./common
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: build common
      run: mvn clean install
    - name: install common
      run: mvn install:install-file -Dfile=./target/common-1.0-SNAPSHOT.jar  -DpomFile=./pom.xml
    - run: |
        cd ../inventory
        pwd
    - name: verify inventory
      run: mvn clean verify
