name: build and push docker image
on:
  push:
    branches: 
      - 'main'
#  release:
#    types: [published]
jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out inventory
      uses: actions/checkout@v2
      with:
        path: './inventory'
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: build common
      run: cd common && mvn clean install
    - name: install common
      run: cd common && mvn install:install-file -Dfile=./target/common-1.0-SNAPSHOT.jar  -DpomFile=./pom.xml
    - name: verify inventory
      run: cd inventory && mvn clean install
#
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_VERSION
        cd inventory
# that's how i do tags:
        docker build -t stiesssh/inventory:v0.1.0 .
        docker push stiesssh/inventory:v0.1.0
# that's how cool kids do tags:       
#        docker build -t stiesssh/inventory:${{ env.RELEASE_VERSION }} .
#        docker push stiesssh/inventory:${{ env.RELEASE_VERSION }}
