name: build and push docker image
on: push
#  release:
#    types: [published]
jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: set env
      run: |
         echo "TRAM_VERSION=${{secrets.TRAM_VERSION}}" >> $GITHUB_ENV
         echo "JAEGER_VERSION=${{secrets.JAEGER_VERSION}}" >> $GITHUB_ENV
         echo "JACOCO_VERSION=${{secrets.JACOCO_VERSION}}" >> $GITHUB_ENV
         echo "RESILIENCE4J_VERSION=${{secrets.RESILIENCE4J_VERSION}}" >> $GITHUB_ENV
         echo "JUNIT4_VERSION=${{secrets.JUNIT4_VERSION}}" >> $GITHUB_ENV
         echo "TRAM_PARTICIPANT_VERSION=${{secrets.TRAM_PARTICIPANT_VERSION}}" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out inventory
      uses: actions/checkout@v2
      with:
        path: './inventory'
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: build common
      run: cd common && ./mvnw clean install
    - name: install common
      run: cd common && ./mvnw install:install-file -Dfile=./target/common-1.0-SNAPSHOT.jar  -DpomFile=./pom.xml
    - name: install inventory
      run: cd inventory && ./mvnw clean install
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: build and push container
      run: |
        echo ${{ env.RELEASE_VERSION }}
        cd inventory
        docker build -t stiesssh/inventory:${{ env.RELEASE_VERSION }} .
        docker push stiesssh/inventory:${{ env.RELEASE_VERSION }}
